services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

    express-app:
        build:
            context: .
        container_name: express-app
        restart: always
        ports:
            - 8080:8080
        env_file:
            - .env
        depends_on:
            - mysql

volumes:
    mysql_data:
